Fix crossbuild script to continue after invalid arch.
oduwsdl/MemGator pull request #136
Opened 2021-04-02 21:00 UTC by machawk1

This PR accounts for invalid architectures in the crossbuild script and closes #135.

I adjusted the bash script to print a message if the architecture combo used to build fails. Executing the revised script produces the binaries in /tmp/mgbins: memgator-darwin-amd64, memgator-windows-386.exe, memgator-linux-386, memgator-windows-amd64.exe, memgator-linux-amd64.

2021-04-02 21:34 UTC, ibnesayeed requested changes
I did not like the idea of inconsistent builds and silently ignoring the error. This change will let the script exit with success even if the build failed due to reasons other than the OS/Arch combo not supported.

Let's just get rid of the 32 bit builds for all OSes and change line 14 to:

```
arcs="amd64"
```

2021-04-02 21:37 UTC, machawk1 commented
@ibnesayeed A subsequent PR will be to add support for arm64, which Apple silicon uses (see also https://github.com/machawk1/wail/issues/494), but I am unsure if the other permutations exist (e.g., arm64+linux, arm64+windows).

Any way you accomplish it, there needs to be a change for the script to work as expected with the currently listed permutations.

2021-04-02 21:45 UTC, ibnesayeed commented
I would simply remove the loop and include 3-4 flat lines with commands for each combination we want.

2021-04-04 00:30 UTC, ibnesayeed commented
@machawk1 I have pushed a few changes to this branch. See if that works for you.

2021-04-04 00:32 UTC, ibnesayeed approved these changes

2021-04-05 15:22 UTC, machawk1 commented
@ibnesayeed Your changes work for me and produce three binaries. What are your thoughts on adding `darwin/arm64` while we are at it to support Apple Silicon...or would you rather that be a separate PR?

2021-04-05 18:46 UTC, ibnesayeed commented
Please go ahead and add the new platform entry in this PR. Also, please test the binary, if you have that machine available.

2021-04-05 18:53 UTC, machawk1 commented
@ibnesayeed I built for the additional platform and did some rudimentary tests with the binary on a machine with that platform. If you want some further tests or for me to run automated tests on the additional platform, let me know.

2021-04-05 20:43 UTC, ibnesayeed commented
I have fixed the GH Workflow issues and this is good to go.

2021-04-05 20:43 UTC, merged

2021-04-05 20:45 UTC, machawk1 commented
@ibnesayeed Good! I meant to mention that after the last PR but also experienced an issue with Golang resolving the mflag package in my older Golang installation prior to submitting this PR/issue.

2021-04-05 23:45 UTC, ibnesayeed commented
@machawk1 is the `mflag` package resolution still an issue? Things were changed when Golang moved to modules for dependencies. I noticed that `go.mod` file is still referencing to Go 1.14, which should be changed to 1.16 now.

2021-04-06 00:17 UTC, machawk1 commented
@ibnesayeed After updating my Go version, the `mflag` issues was no longer reported. Of note, though likely insignificant, I have yet to build MemGator on arm64 for lack of the environment (still a new machine). In the above, I built it on amd64, transferred the arm64 binary to the arm64 machine, and ran it with success.